### ISSUE TITLE
Deployment broken?

### ISSUE THREAD

**Issue by siwelwerd** [code4mathorg/github-for-mathematicians#25]
I am getting a 404 page not found for https://g4m.clontz.org/ .

**Comment by StevenClontz** [comment]
We're at https://g4m.code4math.org and only http://g4m.clontz.org redirects. I should fix that.

**Comment by siwelwerd** [comment]
I thought you might have moved it but couldn't find the new link on Google, and the repository info still says g4m.clontz.org so you'll want to update that too.

**Comment by StevenClontz** [comment]
I believe this is now resolved. And I need to remember the tricks I set up at https://github.com/StevenClontz/g4m.clontz.org-redirect for the next time this happens.
