### ISSUE TITLE
No Typo

### ISSUE THREAD

**Issue by Reben80** [code4mathorg/github-for-mathematicians#36]
There is no typo  in this [Paragraph](https://g4m.code4math.org/ch-first-repo.html#sec-creating-the-repo-4) 
https://g4m.code4math.org/ch-first-repo.html#sec-creating-the-repo-4

**Comment by StevenClontz** [comment]
Indeed, there is not! :-D Thanks for trying out the issues feature - please open a new issue when a typo or another proposed improvement is found.
